# DockerFile for a plain Firedrake suitable for testing Firedrake components and applications

FROM firedrakeproject/firedrake-env:latest

# This DockerFile is looked after by
MAINTAINER David Ham <david.ham@imperial.ac.uk>

USER firedrake
WORKDIR /home/firedrake

# Now install Firedrake.
#ENV PETSC_CONFIGURE_OPTIONS "COPTFLAGS='-O3 -g' CXXOPTFLAGS='-O3 -g'"
COPY ./firedrake-install /home/firedrake/
RUN bash -c "python3 firedrake-install --no-package-manager --verbose --disable-ssh"
